### ISSUE TITLE
Slack not working on Wayland KDE

### ISSUE THREAD

**Issue by galloramiro** [flathub/com.slack.Slack#265]
### Slack
Slack version: 4.37.77
Release date: 11/02/2024

### System 
Operating System: Fedora Linux 39
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.7.4-200.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × 11th Gen Intel® Core™ i5-1135G7 @ 2.40GHz
Memory: 23,2 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
Manufacturer: Dell Inc.
Product Name: Inspiron 15 3511

## Bug description
Slack some times it's freezing with a black screen, other times disconnect my accounts and I need to re connect them.
If I left this black screem goes I get a pop up that ask me to reload the app or kill it, but nothing seems to work. 
Right now after restart it's keeping the black screen.
![Screenshot_20240221_102117](https://github.com/flathub/com.slack.Slack/assets/25160187/f211316b-53bd-40a8-a952-110ec455a834)

**Comment by ZVNexus** [comment]
> other times disconnect my accounts and I need to re connect them

Likely related to the libsecret changes recently, shouldn't ask you again.

Also is this only happening on Wayland?

**Comment by hellsworth** [comment]
I also have this issue with wayland kde and the slack flatpak. When run from the CLI, here are the logs and then it crashes:
```
$ flatpak run com.slack.Slack
Initializing local storage instance
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
LaunchProcess: failed to execvp:
xdg-settings
```
When I watch `~/.var/app/com.slack.Slack/config/Slack/logs/default/electron_debug.log`, this is the only thing added when slack is launched and crashes:
```
[4:0229/130243.422042:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
```
But bluez seems totally unrelated to slack so idk. This line *is* consistently added on launching slack though.

**Comment by ZVNexus** [comment]
@hellsworth What GPU are you using?

**Comment by ZVNexus** [comment]
@hellsworth Mind testing this PR?
https://github.com/flathub/com.slack.Slack/pull/275

Some GPUs don't play well with the sandbox so want to test this first.

**Comment by hellsworth** [comment]
yes i will happily test the pr. what's the command to build it?

**Comment by hellsworth** [comment]
nvm i see the build now in the pr.. I'll test it here in a bit

**Comment by hellsworth** [comment]
I installed the test branch of slack from #275 and ran it from the terminal. It still crashed and here's the stdout:

```
$ flatpak run com.slack.Slack
Initializing local storage instance
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
LaunchProcess: failed to execvp:
xdg-settings
Error occurred in handler for 'GET_MEDIA_ACCESS_STATUS': TypeError: ae.systemPreferences.getMediaAccessStatus is not a function
    at /app/extra/resources/app.asar/dist/main.bundle.js:94:41813
    at yu (/app/extra/resources/app.asar/dist/main.bundle.js:5:5872)
    at /app/extra/resources/app.asar/dist/main.bundle.js:5:6606
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78183)
    at WebContents.emit (node:events:514:28)
    at WebContents.emit (node:domain:488:12)
    at T.emit (/app/extra/resources/app.asar/dist/main.bundle.js:174:10674)
Error occurred in handler for 'GET_MEDIA_ACCESS_STATUS': TypeError: ae.systemPreferences.getMediaAccessStatus is not a function
    at /app/extra/resources/app.asar/dist/main.bundle.js:94:41813
    at yu (/app/extra/resources/app.asar/dist/main.bundle.js:5:5872)
    at /app/extra/resources/app.asar/dist/main.bundle.js:5:6606
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78183)
    at WebContents.emit (node:events:514:28)
    at WebContents.emit (node:domain:488:12)
    at T.emit (/app/extra/resources/app.asar/dist/main.bundle.js:174:10674)
Error occurred in handler for 'GET_MEDIA_ACCESS_STATUS': TypeError: ae.systemPreferences.getMediaAccessStatus is not a function
    at /app/extra/resources/app.asar/dist/main.bundle.js:94:41813
    at yu (/app/extra/resources/app.asar/dist/main.bundle.js:5:5872)
    at /app/extra/resources/app.asar/dist/main.bundle.js:5:6606
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78183)
    at WebContents.emit (node:events:514:28)
    at WebContents.emit (node:domain:488:12)
    at T.emit (/app/extra/resources/app.asar/dist/main.bundle.js:174:10674)
```

**Comment by nerumo** [comment]
For me, there was another issue. I had to add the permission for the wayland socket to make the start work. After that, it went well

![image](https://github.com/flathub/com.slack.Slack/assets/8597645/0acd1768-d812-403b-8249-89e1b479ae69)

**Comment by ZVNexus** [comment]
> For me, there was another issue. I had to add the permission for the wayland socket to make the start work. After that, it went well

If you do this, it will run the app as a native Wayland app (vs just running under XWayland). Keep in mind the list of regressions in https://github.com/flathub/com.slack.Slack/issues/183#issuecomment-1902686110

There were some KDE specific Wayland bugs when I was doing some testing a bit ago, one of them had to do with the app not being linked to the desktop file which led to it's icon not showing up in taskbar or overview, just having a blank Wayland icon.

**Comment by nerumo** [comment]
> > For me, there was another issue. I had to add the permission for the wayland socket to make the start work. After that, it went well
> 
> If you do this, it will run the app as a native Wayland app (vs just running under XWayland). Keep in mind the list of regressions in [#183 (comment)](https://github.com/flathub/com.slack.Slack/issues/183#issuecomment-1902686110)
> 
> There were some KDE specific Wayland bugs when I was doing some testing a bit ago, one of them had to do with the app not being linked to the desktop file which led to it's icon not showing up in taskbar or overview, just having a blank Wayland icon.

ah, thanks for the info. I'm used to those missing icons, there's KDE working around this with window rules.
![image](https://github.com/flathub/com.slack.Slack/assets/8597645/865d24d5-509a-41c1-9d2d-5965f98fa72e)

I'll keep it in mind, so far it works for me

**Comment by hellsworth** [comment]
I can also say that enabling these socket permissions (in flatseal) work for me
![image](https://github.com/flathub/com.slack.Slack/assets/12970280/f2d7b284-1b38-498f-aa5f-d10bb3fc865e)

**Comment by AKoskovich** [comment]
Retest on latest vesion, Slack is now defaulting to Wayland if it is available.
