### ISSUE TITLE
Unable to open files: GET_MEDIA_ACCESS_STATUS

### ISSUE THREAD

**Issue by filipenf** [flathub/com.slack.Slack#277]
I'm unable to open files, when I click on the file or "Open containing folder" nothing happens. Running via command line I get this in the output when I click on the file:

```
Error occurred in handler for 'GET_MEDIA_ACCESS_STATUS': TypeError: ae.systemPreferences.getMediaAccessStatus is not a function
    at /app/extra/resources/app.asar/dist/main.bundle.js:94:41813
    at yu (/app/extra/resources/app.asar/dist/main.bundle.js:5:5872)
    at /app/extra/resources/app.asar/dist/main.bundle.js:5:6606
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78183)
    at WebContents.emit (node:events:514:28)
    at WebContents.emit (node:domain:488:12)
    at T.emit (/app/extra/resources/app.asar/dist/main.bundle.js:174:10674)
```

and when I click to open the dir:

```
[4:0411/091321.170001:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.portal.OpenURI.OpenDirectory: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.NoReply: Remote peer disconnected
```

**Comment by ZVNexus** [comment]
The first error is unrelated, and I can't reproduce the second. I can open files with "Open containing folder".

What distribution are you on, and what desktop environment?

**Comment by filipenf** [comment]
With regard to the first error you're right, I thought it only happened when I clicked on a file but that's not the case it happens during startup also.

I should have mentioned on the original report 😐  my distro is Fedora 39 with gnome (on X11 not wayland).

**Comment by filipenf** [comment]
Another data point: I just installed slack from the RPM for a quick test and it works as expected

**Comment by ZVNexus** [comment]
> I should have mentioned on the original report 😐 my distro is Fedora 39 with gnome (on X11 not wayland).

Fedora 39 is scheduled to reach EoL next month, let me know if you can still reproduce this on Fedora 40, or 41 when it releases.

**Comment by bayang** [comment]
same issue here, fedora 40 kde wayland.

Slack info :  4.40.133 64-bit 
9999707b2e358dfb274c6b8397c8b5
aee58afedd@1729513255

I can no longer use the file picker to attach files, only the downloads folder is accessible. I tried to enable wayland socket just in case and it did not solve the problem.

During startup I have these logs : 
```
flatpak run com.slack.Slack                                              
Initializing local storage instance
Starting Sentry
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
LaunchProcess: failed to execvp:
xdg-settings
Error occurred in handler for 'GET_MEDIA_ACCESS_STATUS': TypeError: _e.systemPreferences.getMediaAccessStatus is not a function
    at /app/extra/resources/app.asar/dist/main.bundle.js:99:24566
    at new Promise (<anonymous>)
    at S3 (/app/extra/resources/app.asar/dist/main.bundle.js:99:24508)
    at /app/extra/resources/app.asar/dist/main.bundle.js:99:27534
    at Oh (/app/extra/resources/app.asar/dist/main.bundle.js:68:5538)
    at /app/extra/resources/app.asar/dist/main.bundle.js:68:6580
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86094)
    at WebContents.emit (node:events:519:28)
    at WebContents.emit (node:domain:488:12)
    at A.emit (/app/extra/resources/app.asar/dist/main.bundle.js:183:10717)
Error occurred in handler for 'GET_MEDIA_ACCESS_STATUS': TypeError: _e.systemPreferences.getMediaAccessStatus is not a function
    at /app/extra/resources/app.asar/dist/main.bundle.js:99:24566
    at new Promise (<anonymous>)
    at S3 (/app/extra/resources/app.asar/dist/main.bundle.js:99:24508)
    at /app/extra/resources/app.asar/dist/main.bundle.js:99:27534
    at Oh (/app/extra/resources/app.asar/dist/main.bundle.js:68:5538)
    at /app/extra/resources/app.asar/dist/main.bundle.js:68:6580
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86094)
    at WebContents.emit (node:events:519:28)
    at WebContents.emit (node:domain:488:12)
    at A.emit (/app/extra/resources/app.asar/dist/main.bundle.js:183:10717)
Error occurred in handler for 'GET_MEDIA_ACCESS_STATUS': TypeError: _e.systemPreferences.getMediaAccessStatus is not a function
    at /app/extra/resources/app.asar/dist/main.bundle.js:99:24566
    at new Promise (<anonymous>)
    at S3 (/app/extra/resources/app.asar/dist/main.bundle.js:99:24508)
    at /app/extra/resources/app.asar/dist/main.bundle.js:99:27534
    at Oh (/app/extra/resources/app.asar/dist/main.bundle.js:68:5538)
    at /app/extra/resources/app.asar/dist/main.bundle.js:68:6580
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86094)
    at WebContents.emit (node:events:519:28)
    at WebContents.emit (node:domain:488:12)
    at A.emit (/app/extra/resources/app.asar/dist/main.bundle.js:183:10717
```

And if I open the file picker this line is logged : 
```
(slack:4): Gdk-WARNING **: 15:55:36.988: Server is missing xdg_foreign support

```

**Comment by Edu4rdSHL** [comment]
Is this still a problem? I haven't experienced it lately

**Comment by filipenf** [comment]
Have not had it in recent versions. I'll close the issue
